---

- name: Check installed {{ bdi__name }} version
  shell: 'cat {{ bdi__version_file }} || echo "0.0.0"'
  register: version_cat
  changed_when: 'version_cat.stdout | version_compare(bdi__version, "<")'

- name: Install / Update {{ bdi__name }} version
  when: 'version_cat.stdout | version_compare(bdi__version, "<")'
  vars:
    old_version: '{{ version_cat.stdout }}'
  include: install.yml

- name: Create symlinks of executables into path
  file:
    state: link
    src: '{{ bdi__install_path }}/{{ item }}'
    path: '{{ bdi__link_path }}/{{ item }}'
  with_items: '{{ bdi__executables }}'
  when: 'bdi__executables|d([])|length > 0'

- name: export variables
  set_fact: >
    bdi__{{ bdi__name }}__version_file={{ bdi__version_file }}
    bdi__{{ bdi__name }}__install_path_base={{ bdi__install_path_base }}
    bdi__{{ bdi__name }}__install_path_dir={{ bdi__install_path_dir }}
    bdi__{{ bdi__name }}__install_path={{ bdi__install_path }}
    bdi__{{ bdi__name }}__updated={{ version_cat.stdout | version_compare(bdi__version, "<") | bool }}
